version: '3'
services:
  mysqldb:
    image: mysql:5.7
    #    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: khaddemdb
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - /home/db:/var/lib/mysql
  khaddem-app:
    build:
      context: .
      dockerfile: Dockerfile
#    restart: always
    #    environment:
    #      spring.datasource.url: jdbc:mysql://mysqldb:3306/khaddemdb?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    ports:
      - "8089:8089"
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
  khaddem-frontend:
    image: alaeddinehammouda/angular-app:latest
    ports:
      - "4200:80"
#volumes:
#  khaddemdb:


